name: phpcs

on: [pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - name: dokcer-compose up
        run: |
          docker-compose up -d
      - name: composer install
        run: |
          docker compose exec app composer install
      - name: Run CodeSniffer
        run: |
          docker compose exec app composer cs-check
